PROG=	pax
MAN=	cpio.1 pax.1
SRCS=	ar_io.c \
	ar_subs.c \
	buf_subs.c \
	cache.c \
	cpio.c \
	file_subs.c \
	ftree.c \
	gen_subs.c \
	getoldopt.c \
	options.c \
	pat_rep.c \
	pax_format.c \
	pax.c \
	sel_subs.c \
	tables.c \
	tar.c \
	tty_subs.c

LDADD+=-liosexec

BINDIR=/bin

.include <bsd.prog.mk>
