SUBDIR=	banner \
	cat \
	col \
	colrm \
	column \
	comm \
	csplit \
	cut \
	ed \
	ee \
	expand \
	fmt \
	fold \
	grep \
	head \
	join \
	lam \
	look \
	md5 \
	nl \
	paste \
	pr \
	rev \
	rs \
	sed \
	sort \
	split \
	tail \
	tr \
	ul \
	unexpand \
	uniq \
	unvis \
	vis \
	wc

.include <bsd.subdir.mk>
