SUBDIR=	arp.tproj \
	cfilutil \
	dnctl \
	ecnprobe \
	frame_delay \
	ifconfig.tproj \
	ip6addrctl.tproj \
	kdumpd.tproj \
	mnc.tproj \
	mptcp_client \
	mtest.tproj \
	ndp.tproj \
	netstat.tproj \
	ping.tproj \
	ping6.tproj \
	pktapctl \
	pktmnglr \
	rarpd.tproj \
	route.tproj \
	rtadvd.tproj \
	rtsol.tproj \
	spray.tproj \
	traceroute.tproj \
	traceroute6.tproj

.include <bsd.subdir.mk>
