SUBDIR=	chflags \
	chmod \
	chown \
	cksum \
	compress \
	cp \
	dd \
	df \
	du \
	gzip \
	install \
	ipcrm \
	ipcs \
	ln \
	ls \
	mkdir \
	mkfifo \
	mknod \
	mtree \
	mv \
	pathchk \
	pax \
	rm \
	rmdir \
	rmt \
	shar \
	stat \
	touch

.include <bsd.subdir.mk>
