PROG=	ifconfig
MAN=	ifconfig.8
SRCS=	af_inet.c \
	af_inet6.c \
	af_link.c \
	if6lowpan.c \
	ifbond.c \
	ifbridge.c \
	ifclone.c \
	ifconfig.c \
	iffake.c \
	ifmedia.c \
	ifvlan.c \
	nexus.c

BINDIR=/sbin

.include <bsd.prog.mk>
