SUBDIR=	dev_mkdb.tproj \
	edquota.tproj \
	fdisk.tproj \
	fsck.tproj \
	fstyp.tproj \
	fuser.tproj \
	mount_devfs.tproj \
	mount_fdesc.tproj \
	mount.tproj \
	quota.tproj \
	quotacheck.tproj \
	quotaon.tproj \
	repquota.tproj \
	setclass.tproj \
	vndevice.tproj \
	vsdbutil.tproj

.include <bsd.subdir.mk>
