# $FreeBSD$

SCRIPTS=generic.sh
SCRIPTSNAME=alias
MAN=builtin.1

LINKS=	${BINDIR}/alias ${BINDIR}/bg \
	${BINDIR}/alias ${BINDIR}/cd \
	${BINDIR}/alias ${BINDIR}/command \
	${BINDIR}/alias ${BINDIR}/fc \
	${BINDIR}/alias ${BINDIR}/fg \
	${BINDIR}/alias ${BINDIR}/getopts \
	${BINDIR}/alias ${BINDIR}/hash \
	${BINDIR}/alias ${BINDIR}/jobs \
	${BINDIR}/alias ${BINDIR}/read \
	${BINDIR}/alias ${BINDIR}/type \
	${BINDIR}/alias ${BINDIR}/ulimit \
	${BINDIR}/alias ${BINDIR}/umask \
	${BINDIR}/alias ${BINDIR}/unalias \
	${BINDIR}/alias ${BINDIR}/wait

MLINKS=	builtin.1 alias.1 \
	builtin.1 cd.1 \
	builtin.1 command.1 \
	builtin.1 fc.1 \
	builtin.1 fg.1 \
	builtin.1 getopts.1 \
	builtin.1 hash.1 \
	builtin.1 jobs.1 \
	builtin.1 read.1 \
	builtin.1 type.1 \
	builtin.1 ulimit.1 \
	builtin.1 umask.1 \
	builtin.1 unalias.1 \
	builtin.1 wait.1

.include <bsd.prog.mk>
